deploy:
  provider: heroku
  api_key:
    secure: obeF0k8g7ML/Iw/LsRdl5nGZoxB11KUB+wipCNoCVwUY3+XfAX4XlN6WlnbbdxALrtCdI7hsmu6mMvyksU47iBx05nDog2wNvGFTUlJz1U/fmPOYvR02yusSJ59F56kxzvC4TavU1Ph9qnHeeGJ0VvyuufP9/H+kdSQtDgoe1cB9Wl/Q4X86t9WQD/GTQywbPIf1qM0OECrWGbKQxdk8LIfAQMR1NyXhg8BTEaAaUaBxOPwcQffDOjTzNtbuzwdpjZ1fHuz4A+gmW6jv8tXiqX1Ww9EQSqD0RgIgg5ebDAGL86mrIOA4c17LtUDkDA3EI58Di0IxPmUcgsVVu/v1A/FbHpymaOUnqFG0ItbIV0jmCUzdyy9eUTsud+f7FPwsYSpxzO4+yk47x9gnzhGkINXUChBe0FKwmHZt1/E+zKGsonyPPIMsZ3SpDuhLpjFcO8mJmbVWWVDPrOhwPWcFLnokFJuVgy1VxZOyzXBMtDCa5g94ac03AxVWviBIcobpWSFyHGtlefHnqCye4xzqxjWwMss/HFYvBf2zfNaLEpxA5lbZg7Ki5SzgI+gMdqIJJ6UWQC/zmCbRGFT82fGkgRCpGGK1crMgLyaoCIxwcW01HsK3XfhDLVtxDraChF2l08D4GGm5IWk2BhziJFXTMmiTW+G1UThAdx25prlcTsM=
  app: Q
  on:
    repo: Rad-Hacks/Q
language: node_js
node_js:
- '7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
